### ISSUE TITLE
Gazebo Rendering Dependencies

### ISSUE THREAD

**Issue by marrts** [tesseract-robotics/tesseract_qt#47]
I was updating to the latest version to run things in ROS and had to update my apt repository for the latest gazebo packages for rendering. Could the rendering and studio code be shifted to the https://github.com/tesseract-robotics/tesseract_gui package so that we don't have these unnecessary dependencies if we just want to use the RVIZ interface?

**Comment by Levi-Armstrong** [comment]
The intent of tesseract is to be ros agnostic so the rendering provided in tesseract_qt is what I consider the default for tesseract moving forward. The tesseract_gui will be deprecated/archived soon.

**Comment by marrts** [comment]
I understand the convenience of having the interface that is completely separated from ROS and the convenience of the widgets and that interface being developed in the same package, but it seems like in the current implementation it is coming at a cost of making running it with ROS more complicated, which I think should also be straight forward to do. I ran into issues updating and I see [this issue](https://github.com/tesseract-robotics/tesseract_qt/issues/45) as well, so I suspect I won't be the last. In my head I see the layout as:
### Core Functionality
- tesseract
- tesseract_planning
### Widgets
- tesseract_qt
### Interface
- tesseract_gui (ROS agnostic)
- tesseract_ros
- tesseract_ros2

**Comment by Levi-Armstrong** [comment]
This issue only popped up because this is using a new release of gazebo but the packages have not been added to rosdep. After these have been release in ros, things should also work as normal. 

If you don't want the added dependency then I would be fine with adding a CMake option to disable building these components in this package. I am not a fan of using separate package or repositories to separate dependencies because this is a ROS limitation not a Ubuntu Debian or Windows packaging limitation.
